-- Zenyra HH diagnostics patch

alter table if exists hh_plate_sessions
  add column if not exists specialist_copay_awareness text,
  add column if not exists open_to_protection_options boolean,
  add column if not exists admin_qualified boolean,
  add column if not exists sales_qualified boolean,
  add column if not exists problem_acknowledged boolean,
  add column if not exists emotional_pain_expressed boolean,
  add column if not exists urgency_present boolean,
  add column if not exists affordability_confirmed boolean,
  add column if not exists recommendation_reached boolean,
  add column if not exists trial_close_attempted boolean,
  add column if not exists buying_signals_present boolean,
  add column if not exists primary_loss_reason text,
  add column if not exists secondary_loss_reason text,
  add column if not exists primary_objection text,
  add column if not exists secondary_objection text,
  add column if not exists breakdown_point text,
  add column if not exists objection_handled_effectively text,
  add column if not exists likely_root_cause text,
  add column if not exists call_momentum_score numeric default 0,
  add column if not exists pain_score numeric default 0,
  add column if not exists sales_readiness_score numeric default 0,
  add column if not exists objection_risk_score numeric default 0,
  add column if not exists plate_progress jsonb default '{}'::jsonb;

alter table if exists hh_calls
  add column if not exists admin_qualified boolean,
  add column if not exists sales_qualified boolean,
  add column if not exists primary_loss_reason text,
  add column if not exists secondary_loss_reason text,
  add column if not exists primary_objection text,
  add column if not exists secondary_objection text,
  add column if not exists breakdown_point text,
  add column if not exists problem_acknowledged boolean,
  add column if not exists emotional_pain_expressed boolean,
  add column if not exists urgency_present boolean,
  add column if not exists affordability_confirmed boolean,
  add column if not exists recommendation_reached boolean,
  add column if not exists trial_close_attempted boolean,
  add column if not exists buying_signals_present boolean,
  add column if not exists objection_handled_effectively text,
  add column if not exists likely_root_cause text,
  add column if not exists call_momentum_score numeric default 0,
  add column if not exists pain_score numeric default 0,
  add column if not exists sales_readiness_score numeric default 0,
  add column if not exists objection_risk_score numeric default 0,
  add column if not exists plate_progress jsonb default '{}'::jsonb;

alter table if exists hh_dispositions
  add column if not exists admin_qualified boolean,
  add column if not exists sales_qualified boolean,
  add column if not exists primary_loss_reason text,
  add column if not exists secondary_loss_reason text,
  add column if not exists primary_objection text,
  add column if not exists secondary_objection text,
  add column if not exists breakdown_point text,
  add column if not exists problem_acknowledged boolean,
  add column if not exists emotional_pain_expressed boolean,
  add column if not exists urgency_present boolean,
  add column if not exists affordability_confirmed boolean,
  add column if not exists recommendation_reached boolean,
  add column if not exists trial_close_attempted boolean,
  add column if not exists buying_signals_present boolean,
  add column if not exists objection_handled_effectively text,
  add column if not exists likely_root_cause text,
  add column if not exists call_momentum_score numeric default 0,
  add column if not exists pain_score numeric default 0,
  add column if not exists sales_readiness_score numeric default 0,
  add column if not exists objection_risk_score numeric default 0,
  add column if not exists plate_progress jsonb default '{}'::jsonb;

alter table if exists hh_leads
  add column if not exists latest_primary_loss_reason text,
  add column if not exists latest_primary_objection text,
  add column if not exists latest_breakdown_point text,
  add column if not exists latest_likely_root_cause text;
